# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: mavchain.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Provider1
    Domain: provider1.mavchain.com
    # EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: HP1
    Domain: hp1.mavchain.com
    # EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: HP2
    Domain: hp2.mavchain.com
    # EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: HP3
    Domain: hp3.mavchain.com
    # EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
